version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    networks:
      - mysql-network
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d


networks:
  mysql-network:
    driver: bridge