version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    networks:
      - mysql-network
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d

  server:
    image: node:16.14.0
    working_dir: /usr/src/app
    ports: 
      - "3000:3000"
    tty: true
    volumes:
      - ../api:/usr/src/app
    command: bash -c "npm install && npm install nodemon -g && nodemon src/server.js"

networks:
  mysql-network:
    driver: bridge